fedora:
    stage: build
    image: fedora
    script:
        - ./bin/ci/build-and-test.sh


pages:
    stage: build
    image: fedora
    script:
        - ./bin/ci/doxygen.sh
    artifacts:
        paths:
            - html


cppcheck:
    stage: build
    image: fedora
    script:
        - ./bin/ci/cppcheck.sh
