fedora:
    stage: build
    image: fedora
    script:
        - ./bin/ci/build-and-test.sh


pages:
    stage: build
    image: fedora
    script:
        - ./bin/ci/doxygen.sh
    artifacts:
        paths:
            - public
    only:
    - master

doxygen:
    stage: build
    image: fedora
    script:
        - ./bin/ci/doxygen.sh
    except:
        - master


cppcheck:
    stage: build
    image: fedora
    script:
        - ./bin/ci/cppcheck.sh
